theme: jekyll-theme-slate
name: React Platformula
description: A library for building cross-platform apps
url: https://uvop.github.io
baseurl: /react-platformula
permalink: /blog/:year/:month/:day/:title.html
paginate_path: /blog/page:num/
paginate: 5
timezone: America/Los_Angeles
defaults:
- scope:
    path: docs
    type: pages
  values:
    layout: docs
    sectionid: docs
exclude:
- Gemfile
- README.md
sass:
  sass_dir: ./_sass
gems:
- jekyll-redirect-from
- jekyll-paginate


